<a href="https://colab.research.google.com/github/ercb312/TensorFlow101/blob/main/boston_realestate_model_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 보스턴 집값 예측
*   https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv



In [13]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 1.과거의 데이터를 준비한다
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [ ]:
#독립변수, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
# 2.모델의 구조를 만든다
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [14]:
# 3.데이터로 모델을 학습(Fit)한다
model.fit(독립, 종속, epochs=10000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 22.9386
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 23.9853
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 23.2428
Epoch 4/10
16/16 [==============================] - 0s 4ms/step - loss: 23.3062
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 23.3987
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 22.8411
Epoch 7/10
16/16 [==============================] - 0s 3ms/step - loss: 23.4674
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 23.1145
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 23.7070
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 23.3651


In [15]:
#모델을 이용한다
model.predict(독립[0:5]) #스라이싱 사용 => 첫번째 독립변수부터 다섯째까지 사용

1/1 [==============================] - 0s 17ms/step


array([[29.354778],
       [24.35439 ],
       [30.670216],
       [29.139654],
       [28.704765]], dtype=float32)

In [ ]:
종속[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [16]:
model.predict(독립[5:10])

1/1 [==============================] - 0s 19ms/step


array([[25.132244],
       [21.85127 ],
       [18.789433],
       [10.662037],
       [18.139261]], dtype=float32)

In [ ]:
종속[5:10]

medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

In [17]:
#모델의 수식 확인
model.get_weights()

[array([[-0.0974015 ],
        [ 0.04510253],
        [-0.00993276],
        [ 2.6381822 ],
        [-6.1646185 ],
        [ 4.974799  ],
        [-0.00747167],
        [-1.1574702 ],
        [ 0.22504458],
        [-0.01122201],
        [-0.6134102 ],
        [ 0.01181841],
        [-0.47557476]], dtype=float32),
 array([14.55444], dtype=float32)]

집값 = -0.09169247 * x1 + 0.04889499 * x2 + -0.01794892 * x3 + 2.6560414 * x4 + -2.7423863 * x5 + 5.2396145 * x6 + -0.00926467 * x7 + -1.0775577 * x8 + 0.20224835 * x9 + -0.01021173 * x10 + -0.5288887 * x11 + 0.01310567 * x12 + -0.4633926 * x13 + 14.55444
      